### PR TITLE
Allow MongoDB connection string to be specified elsewhere

### PR DESCRIPTION
**Pull request by ducas**
Provide extra configuration options so that a developer can re-use an existing connection string or app setting for their MongoDB URL

### CODE REVIEW

**Comment by nathanaeljones** [comment]
Hi @ducas, if you can release your contributions under Apache terms, we can merge this into v4.

**Comment by ducas** [comment]
I release these contributions under the terms of the Imazen Contributor Agreement V1.0 
(http://imageresizing.net/licenses/contribute), the terms of which I accept and agree.
Ducas Francis
1/05/2015

**Comment by nathanaeljones** [comment]
Thanks! Have you seen our new providers in v4 (develop branch)? They're quite a bit simpler.

**Comment by ducas** [comment]
Haven't used it since I submitted this PR... :-) I'll definitely check it out.

**Comment by lilith** [comment]
Will re-open if there is new activity on this.

**Pull request closed without merging**
