### PR TITLE
PdfiumRenderer PDF rendering plugin based on the PDFium project

### PR DESCRIPTION
**Pull request by pvginkel**
This pull request contains a new plugin for rendering PDF pages using the Google PDFium library. The code is based on the original PdfRenderer and exposes roughly the same functionality.

The following settings can be specified using the query string settings:

* `page`: The page to render;
* `width`, `height`, `maxwidth`, `maxheight`: Determine the height and width of the generated image;
* `annotations`: Whether to render annotations;
* `lcd`: Whether to optimize text for displaying on LCD screens;
* `grayscale`: Whether to output a grayscale image;
* `halftone`: Whether to force halftones;
* `print`: Whether to render for print output;
* `transparent`: Whether to render with a transparent backgroud.

The PdfiumRenderer plugin depends on the [PdfiumViewer](https://github.com/pvginkel/PdfiumViewer) project, which depends on the PDFium project. Documentation located in the `Contrib\PdfiumRenderer\PdfiumRenderer` directory contains a description on how the native PDFium dependencies are used and where they can be downloaded from.

I've used the existing PdfRenderer plugin as a basis for this plugin. The unit tests from that project are included in this one too, with a few additions. The output of a few renderings are verified too against included PNG's. This includes a rendering with transparency (is off by default) based on a sample PDF file from the PdfiumViewer project.

The web project was copied too but is non functional. It has been configured correctly (as far as I can tell), but complains that `ImageResizer.InterceptModule` cannot be found. I've tried the PdfRenderer web project but this gives the same error. Some guidance on this would be appreciated.

I've also included appropriate references to the PdfiumRenderer plugin in the rest of the solution based on how the PdfRenderer plugin was references. I'm not sure whether I got this right.

Currently the PdfiumViewer project has a LGPL v3 license, but this is currently being changed to Apache2. One of the reasons for this is to create a better fit with the license of the ImageResizer project. See https://github.com/pvginkel/PdfiumViewer/issues/14 for the associated issue.

### CODE REVIEW

**Comment by nathanaeljones** [comment]
Thanks! The .png files didn't come through - they're .gitignored by default. If they're under 30kb, it's fine to commit them to the repository. 

The web project may be unable to find ImageResizer.dll, or the project reference might be broken. It was set as a .net 3.5 project, perhaps the .csproj wasn't saved? The issue I ran into with both the unit tests and the web project was that it couldn't locate the native .dlls. They shouldn't be committed to the repository anyway, and we can't rely on a project build step to copy them; doesn't work with test runners or most asp.net projects. I have a native dependency system I'm going to try to upgrade and integrate with this so that I can do unit testing.

**Comment by pvginkel** [comment]
I've added the PNG files. I've also had a look at the AppVeyor error and fixed the output paths of the project. The AppVayor build seems to get beyond building the NuGet packages so that looks OK from what I can see.

About the native DLL's. What I did is put a reference in the project from the inside `/packages` directory. The paths of these are `..\..\..\Packages\PdfiumViewer.1.6.0.0\content\x64\pdfium.dll` and `..\..\..\Packages\PdfiumViewer.1.6.0.0\content\x86\pdfium.dll`. This means that if the NuGet packages get restored, the project should pick up native DLL's from there and use those. I've tested this locally by creating a new checkout, building the PdfiumRenderer project and running the unit tests. Can you tell me how you are running the unit tests so I can correctly fix this?

About the web project: maybe I should just remove it. I've started this plugin as a copy from the PdfRenderer project and thought it was a good idea to copy the web project too. I've had a look at it but I'm not sure how to get it to work. And, even if I would get it to work, the project does not contain any unit tests or sample pages so I can't imagine it being of use. Do you agree?

**Comment by nathanaeljones** [comment]
I'm using the testdriven.net plugin for Visual Studio 2013. I get 


>Test 'ImageResizer.Plugins.PdfiumRenderer.Tests.PdfiumRendererTests.DecodeStream_WhenWidthSpecified_ExpectPage2' failed: System.DllNotFoundException : Unable to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
	at PdfiumViewer.NativeMethods.Imports.FPDF_AddRef()
	at PdfiumViewer.NativeMethods.FPDF_AddRef()
	at PdfiumViewer.PdfLibrary.EnsureLoaded()
	at PdfiumViewer.PdfBufferFile..ctor(Byte[] buffer, Int32 length)
	at PdfiumViewer.PdfFile.Create(Stream stream)
	at PdfiumViewer.PdfDocument.Load(Stream stream)
	PdfiumRendererPlugin.cs(166,0): at ImageResizer.Plugins.PdfiumRenderer.PdfiumRendererPlugin.DecodeStream(Stream s, ResizeSettings settings, String optionalPath)
	PdfiumRendererTests.cs(164,0): at ImageResizer.Plugins.PdfiumRenderer.Tests.PdfiumRendererTests.DecodeStream_WhenWidthSpecified_ExpectPage2()



The web project could be handy for experiments. I just switched the project type to .NET 4.5, added `<validation validateIntegratedModeConfiguration="false"/>`, and it ran. 

To get the web project to load the dll, I had to do that manually:


        [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Ansi)]
        private static extern IntPtr LoadLibrary([MarshalAs(UnmanagedType.LPStr)] string lpFileName);


        protected void Application_Start(object sender, EventArgs e)
        {
            string path = HttpRuntime.AppDomainAppPath;

            if (IntPtr.Size == 4)
                path = Path.Combine(path, "x86");
            else
                path = Path.Combine(path, "x64");

            path = Path.Combine(path, "Pdfium.dll");

            if (File.Exists(path))
                LoadLibrary(path);
 
        }


For the test runner, though, neither the Codebase nor the Assembly Location are useful for locating the native dlls. I'm very interested to know how you got it to work; do you perhaps have then in %PATH%?

**Comment by pvginkel** [comment]
I was running the unit tests with ReSharper. ReSharper runs the unit tests from the output directory but apparently TestDriven.NET doesn't. It copies the DLL's to a new directory and runs from there. The problem was that the native dependencies were located in an `x86` and `x64` sub folder, which weren't copied. I've changed the project configuration such that the x86 native dependency is now copied to the root of the output directory and the unit tests now succeed in TestDriven.NET.

I've applied your suggestions to the web project. Automatic loading of the native dependencies is not something that can be built into PdfiumViewer because of the way ASP.NET works with native dependencies. There is no guaranteed location where I could find the native dependencies. I think that your suggestion is probably the best way to go. You mentioned something about a system to load native dependencies; that may be the best long term solution. For now I've used your code. I've made one small change. The references in the project are links to the `\Packages` directory, so the `x86` and `x64` directories you were referring to in the code were empty. These are now placed in `bin\x86` and `bin\x64`, the output directories. The code has been updated to reflect this.

**Pull request merged**
